version: "3.9"
services:
  main:
    build: ./MAIN
    container_name: surface_editor_main
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./MAIN:/app
      - /app/node_modules
    working_dir: /app
    command: npm run start
