//Following by alphabetical order
const EXTENSIONS_TO_LANGUAGES_MATCHING_LIST = {
  ".c": "c",
  ".cpp": "cpp",
  ".cs": "csharp",
  ".css": "css",
  ".dart": "dart",
  ".gitignore": "plaintext",
  ".go": "go",
  ".groovy": "groovy",
  ".html": "html",
  ".java": "java",
  ".js": "javascript",
  ".jsx": "javascript",
  ".json": "json",
  ".kt": "kotlin",
  ".less": "less",
  ".lua": "lua",
  ".md": "markdown",
  ".php": "php",
  ".py": "python",
  ".rb": "ruby",
  ".rs": "rust",
  ".sass": "sass",
  ".scss": "scss",
  ".sh": "shell",
  ".sql": "sql",
  ".swift": "swift",
  ".ts": "typescript",
  ".tsx": "typescript",
  ".txt": "plaintext",
  ".xml": "xml",
  ".yml": "yaml",
  ".yaml": "yaml",
  ".zsh": "shell",
};

module.exports = { EXTENSIONS_TO_LANGUAGES_MATCHING_LIST };
